/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ACER
 */
public class FRMUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMUsuarios
     */
    public FRMUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTNoid = new javax.swing.JTextField();
        TXTTipoid = new javax.swing.JTextField();
        TXTNombreUs = new javax.swing.JTextField();
        TXTApellidosUs = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Registar un usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGREGAR USUARIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 490, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Tipo de identificacion :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("-----------------------------------------------------");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 270, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("No°Idtentificacion :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Nombre :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 245, 120, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Apellidos :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 30));

        TXTNoid.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(TXTNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));

        TXTTipoid.setForeground(new java.awt.Color(255, 153, 0));
        TXTTipoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTipoidActionPerformed(evt);
            }
        });
        getContentPane().add(TXTTipoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, 30));

        TXTNombreUs.setForeground(new java.awt.Color(255, 153, 0));
        TXTNombreUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreUsActionPerformed(evt);
            }
        });
        getContentPane().add(TXTNombreUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 30));

        TXTApellidosUs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TXTApellidosUs.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(TXTApellidosUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 720, 340));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTTipoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTipoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTipoidActionPerformed

    private void TXTNombreUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreUsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTApellidosUs;
    private javax.swing.JTextField TXTNoid;
    private javax.swing.JTextField TXTNombreUs;
    private javax.swing.JTextField TXTTipoid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
